//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.JAsociacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AsociacionPortBinding", Namespace="http://Servicios/")]
    public partial class Asociacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback nuevoMiembroOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearAsociacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarMiembroOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerAsociacionesPorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambiarTipoMembresiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPublicacionesAsociacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerUsuariosPorAsociacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Asociacion() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_JAsociacion_Asociacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event nuevoMiembroCompletedEventHandler nuevoMiembroCompleted;
        
        /// <remarks/>
        public event crearAsociacionCompletedEventHandler crearAsociacionCompleted;
        
        /// <remarks/>
        public event eliminarMiembroCompletedEventHandler eliminarMiembroCompleted;
        
        /// <remarks/>
        public event obtenerAsociacionesPorUsuarioCompletedEventHandler obtenerAsociacionesPorUsuarioCompleted;
        
        /// <remarks/>
        public event cambiarTipoMembresiaCompletedEventHandler cambiarTipoMembresiaCompleted;
        
        /// <remarks/>
        public event obtenerPublicacionesAsociacionCompletedEventHandler obtenerPublicacionesAsociacionCompleted;
        
        /// <remarks/>
        public event obtenerUsuariosPorAsociacionCompletedEventHandler obtenerUsuariosPorAsociacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool nuevoMiembro([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nickname, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_asociacion) {
            object[] results = this.Invoke("nuevoMiembro", new object[] {
                        nickname,
                        id_asociacion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoMiembroAsync(string nickname, int id_asociacion) {
            this.nuevoMiembroAsync(nickname, id_asociacion, null);
        }
        
        /// <remarks/>
        public void nuevoMiembroAsync(string nickname, int id_asociacion, object userState) {
            if ((this.nuevoMiembroOperationCompleted == null)) {
                this.nuevoMiembroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoMiembroOperationCompleted);
            }
            this.InvokeAsync("nuevoMiembro", new object[] {
                        nickname,
                        id_asociacion}, this.nuevoMiembroOperationCompleted, userState);
        }
        
        private void OnnuevoMiembroOperationCompleted(object arg) {
            if ((this.nuevoMiembroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoMiembroCompleted(this, new nuevoMiembroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crearAsociacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_creador) {
            object[] results = this.Invoke("crearAsociacion", new object[] {
                        nombre,
                        id_creador});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void crearAsociacionAsync(string nombre, int id_creador) {
            this.crearAsociacionAsync(nombre, id_creador, null);
        }
        
        /// <remarks/>
        public void crearAsociacionAsync(string nombre, int id_creador, object userState) {
            if ((this.crearAsociacionOperationCompleted == null)) {
                this.crearAsociacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearAsociacionOperationCompleted);
            }
            this.InvokeAsync("crearAsociacion", new object[] {
                        nombre,
                        id_creador}, this.crearAsociacionOperationCompleted, userState);
        }
        
        private void OncrearAsociacionOperationCompleted(object arg) {
            if ((this.crearAsociacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearAsociacionCompleted(this, new crearAsociacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool eliminarMiembro([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nickname, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_asociacion) {
            object[] results = this.Invoke("eliminarMiembro", new object[] {
                        nickname,
                        id_asociacion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarMiembroAsync(string nickname, int id_asociacion) {
            this.eliminarMiembroAsync(nickname, id_asociacion, null);
        }
        
        /// <remarks/>
        public void eliminarMiembroAsync(string nickname, int id_asociacion, object userState) {
            if ((this.eliminarMiembroOperationCompleted == null)) {
                this.eliminarMiembroOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarMiembroOperationCompleted);
            }
            this.InvokeAsync("eliminarMiembro", new object[] {
                        nickname,
                        id_asociacion}, this.eliminarMiembroOperationCompleted, userState);
        }
        
        private void OneliminarMiembroOperationCompleted(object arg) {
            if ((this.eliminarMiembroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarMiembroCompleted(this, new eliminarMiembroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerAsociacionesPorUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipo) {
            object[] results = this.Invoke("obtenerAsociacionesPorUsuario", new object[] {
                        id_usuario,
                        tipo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerAsociacionesPorUsuarioAsync(int id_usuario, string tipo) {
            this.obtenerAsociacionesPorUsuarioAsync(id_usuario, tipo, null);
        }
        
        /// <remarks/>
        public void obtenerAsociacionesPorUsuarioAsync(int id_usuario, string tipo, object userState) {
            if ((this.obtenerAsociacionesPorUsuarioOperationCompleted == null)) {
                this.obtenerAsociacionesPorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerAsociacionesPorUsuarioOperationCompleted);
            }
            this.InvokeAsync("obtenerAsociacionesPorUsuario", new object[] {
                        id_usuario,
                        tipo}, this.obtenerAsociacionesPorUsuarioOperationCompleted, userState);
        }
        
        private void OnobtenerAsociacionesPorUsuarioOperationCompleted(object arg) {
            if ((this.obtenerAsociacionesPorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerAsociacionesPorUsuarioCompleted(this, new obtenerAsociacionesPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool cambiarTipoMembresia([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nickname, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_asociacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string membresia) {
            object[] results = this.Invoke("cambiarTipoMembresia", new object[] {
                        nickname,
                        id_asociacion,
                        membresia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cambiarTipoMembresiaAsync(string nickname, int id_asociacion, string membresia) {
            this.cambiarTipoMembresiaAsync(nickname, id_asociacion, membresia, null);
        }
        
        /// <remarks/>
        public void cambiarTipoMembresiaAsync(string nickname, int id_asociacion, string membresia, object userState) {
            if ((this.cambiarTipoMembresiaOperationCompleted == null)) {
                this.cambiarTipoMembresiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambiarTipoMembresiaOperationCompleted);
            }
            this.InvokeAsync("cambiarTipoMembresia", new object[] {
                        nickname,
                        id_asociacion,
                        membresia}, this.cambiarTipoMembresiaOperationCompleted, userState);
        }
        
        private void OncambiarTipoMembresiaOperationCompleted(object arg) {
            if ((this.cambiarTipoMembresiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambiarTipoMembresiaCompleted(this, new cambiarTipoMembresiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerPublicacionesAsociacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_asociacion) {
            object[] results = this.Invoke("obtenerPublicacionesAsociacion", new object[] {
                        id_asociacion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPublicacionesAsociacionAsync(int id_asociacion) {
            this.obtenerPublicacionesAsociacionAsync(id_asociacion, null);
        }
        
        /// <remarks/>
        public void obtenerPublicacionesAsociacionAsync(int id_asociacion, object userState) {
            if ((this.obtenerPublicacionesAsociacionOperationCompleted == null)) {
                this.obtenerPublicacionesAsociacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPublicacionesAsociacionOperationCompleted);
            }
            this.InvokeAsync("obtenerPublicacionesAsociacion", new object[] {
                        id_asociacion}, this.obtenerPublicacionesAsociacionOperationCompleted, userState);
        }
        
        private void OnobtenerPublicacionesAsociacionOperationCompleted(object arg) {
            if ((this.obtenerPublicacionesAsociacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPublicacionesAsociacionCompleted(this, new obtenerPublicacionesAsociacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerUsuariosPorAsociacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_asociacion) {
            object[] results = this.Invoke("obtenerUsuariosPorAsociacion", new object[] {
                        id_asociacion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerUsuariosPorAsociacionAsync(int id_asociacion) {
            this.obtenerUsuariosPorAsociacionAsync(id_asociacion, null);
        }
        
        /// <remarks/>
        public void obtenerUsuariosPorAsociacionAsync(int id_asociacion, object userState) {
            if ((this.obtenerUsuariosPorAsociacionOperationCompleted == null)) {
                this.obtenerUsuariosPorAsociacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerUsuariosPorAsociacionOperationCompleted);
            }
            this.InvokeAsync("obtenerUsuariosPorAsociacion", new object[] {
                        id_asociacion}, this.obtenerUsuariosPorAsociacionOperationCompleted, userState);
        }
        
        private void OnobtenerUsuariosPorAsociacionOperationCompleted(object arg) {
            if ((this.obtenerUsuariosPorAsociacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerUsuariosPorAsociacionCompleted(this, new obtenerUsuariosPorAsociacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void nuevoMiembroCompletedEventHandler(object sender, nuevoMiembroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoMiembroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoMiembroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void crearAsociacionCompletedEventHandler(object sender, crearAsociacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearAsociacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearAsociacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void eliminarMiembroCompletedEventHandler(object sender, eliminarMiembroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarMiembroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarMiembroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerAsociacionesPorUsuarioCompletedEventHandler(object sender, obtenerAsociacionesPorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerAsociacionesPorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerAsociacionesPorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cambiarTipoMembresiaCompletedEventHandler(object sender, cambiarTipoMembresiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambiarTipoMembresiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambiarTipoMembresiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerPublicacionesAsociacionCompletedEventHandler(object sender, obtenerPublicacionesAsociacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPublicacionesAsociacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPublicacionesAsociacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerUsuariosPorAsociacionCompletedEventHandler(object sender, obtenerUsuariosPorAsociacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerUsuariosPorAsociacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerUsuariosPorAsociacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591