//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.JPublicacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PublicacionPortBinding", Namespace="http://Servicios/")]
    public partial class Publicacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback comentarPubOperationCompleted;
        
        private System.Threading.SendOrPostCallback agregarPublicacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerComentariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPublicacionesContactosOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPublicacionesIndividualesOperationCompleted;
        
        private System.Threading.SendOrPostCallback comentarPublicacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Publicacion() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_JPublicacion_Publicacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event comentarPubCompletedEventHandler comentarPubCompleted;
        
        /// <remarks/>
        public event agregarPublicacionCompletedEventHandler agregarPublicacionCompleted;
        
        /// <remarks/>
        public event obtenerComentariosCompletedEventHandler obtenerComentariosCompleted;
        
        /// <remarks/>
        public event obtenerPublicacionesContactosCompletedEventHandler obtenerPublicacionesContactosCompleted;
        
        /// <remarks/>
        public event obtenerPublicacionesIndividualesCompletedEventHandler obtenerPublicacionesIndividualesCompleted;
        
        /// <remarks/>
        public event comentarPublicacionCompletedEventHandler comentarPublicacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool comentarPub([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nickname, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_publicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contenido) {
            object[] results = this.Invoke("comentarPub", new object[] {
                        nickname,
                        id_publicacion,
                        contenido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void comentarPubAsync(string nickname, int id_publicacion, string contenido) {
            this.comentarPubAsync(nickname, id_publicacion, contenido, null);
        }
        
        /// <remarks/>
        public void comentarPubAsync(string nickname, int id_publicacion, string contenido, object userState) {
            if ((this.comentarPubOperationCompleted == null)) {
                this.comentarPubOperationCompleted = new System.Threading.SendOrPostCallback(this.OncomentarPubOperationCompleted);
            }
            this.InvokeAsync("comentarPub", new object[] {
                        nickname,
                        id_publicacion,
                        contenido}, this.comentarPubOperationCompleted, userState);
        }
        
        private void OncomentarPubOperationCompleted(object arg) {
            if ((this.comentarPubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.comentarPubCompleted(this, new comentarPubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool agregarPublicacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contenido) {
            object[] results = this.Invoke("agregarPublicacion", new object[] {
                        id_usuario,
                        contenido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void agregarPublicacionAsync(int id_usuario, string contenido) {
            this.agregarPublicacionAsync(id_usuario, contenido, null);
        }
        
        /// <remarks/>
        public void agregarPublicacionAsync(int id_usuario, string contenido, object userState) {
            if ((this.agregarPublicacionOperationCompleted == null)) {
                this.agregarPublicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarPublicacionOperationCompleted);
            }
            this.InvokeAsync("agregarPublicacion", new object[] {
                        id_usuario,
                        contenido}, this.agregarPublicacionOperationCompleted, userState);
        }
        
        private void OnagregarPublicacionOperationCompleted(object arg) {
            if ((this.agregarPublicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarPublicacionCompleted(this, new agregarPublicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerComentarios([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_publicacion) {
            object[] results = this.Invoke("obtenerComentarios", new object[] {
                        id_publicacion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerComentariosAsync(int id_publicacion) {
            this.obtenerComentariosAsync(id_publicacion, null);
        }
        
        /// <remarks/>
        public void obtenerComentariosAsync(int id_publicacion, object userState) {
            if ((this.obtenerComentariosOperationCompleted == null)) {
                this.obtenerComentariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerComentariosOperationCompleted);
            }
            this.InvokeAsync("obtenerComentarios", new object[] {
                        id_publicacion}, this.obtenerComentariosOperationCompleted, userState);
        }
        
        private void OnobtenerComentariosOperationCompleted(object arg) {
            if ((this.obtenerComentariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerComentariosCompleted(this, new obtenerComentariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerPublicacionesContactos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario) {
            object[] results = this.Invoke("obtenerPublicacionesContactos", new object[] {
                        id_usuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPublicacionesContactosAsync(int id_usuario) {
            this.obtenerPublicacionesContactosAsync(id_usuario, null);
        }
        
        /// <remarks/>
        public void obtenerPublicacionesContactosAsync(int id_usuario, object userState) {
            if ((this.obtenerPublicacionesContactosOperationCompleted == null)) {
                this.obtenerPublicacionesContactosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPublicacionesContactosOperationCompleted);
            }
            this.InvokeAsync("obtenerPublicacionesContactos", new object[] {
                        id_usuario}, this.obtenerPublicacionesContactosOperationCompleted, userState);
        }
        
        private void OnobtenerPublicacionesContactosOperationCompleted(object arg) {
            if ((this.obtenerPublicacionesContactosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPublicacionesContactosCompleted(this, new obtenerPublicacionesContactosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerPublicacionesIndividuales([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario) {
            object[] results = this.Invoke("obtenerPublicacionesIndividuales", new object[] {
                        id_usuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPublicacionesIndividualesAsync(int id_usuario) {
            this.obtenerPublicacionesIndividualesAsync(id_usuario, null);
        }
        
        /// <remarks/>
        public void obtenerPublicacionesIndividualesAsync(int id_usuario, object userState) {
            if ((this.obtenerPublicacionesIndividualesOperationCompleted == null)) {
                this.obtenerPublicacionesIndividualesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPublicacionesIndividualesOperationCompleted);
            }
            this.InvokeAsync("obtenerPublicacionesIndividuales", new object[] {
                        id_usuario}, this.obtenerPublicacionesIndividualesOperationCompleted, userState);
        }
        
        private void OnobtenerPublicacionesIndividualesOperationCompleted(object arg) {
            if ((this.obtenerPublicacionesIndividualesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPublicacionesIndividualesCompleted(this, new obtenerPublicacionesIndividualesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool comentarPublicacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_publicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contenido) {
            object[] results = this.Invoke("comentarPublicacion", new object[] {
                        id_usuario,
                        id_publicacion,
                        contenido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void comentarPublicacionAsync(int id_usuario, int id_publicacion, string contenido) {
            this.comentarPublicacionAsync(id_usuario, id_publicacion, contenido, null);
        }
        
        /// <remarks/>
        public void comentarPublicacionAsync(int id_usuario, int id_publicacion, string contenido, object userState) {
            if ((this.comentarPublicacionOperationCompleted == null)) {
                this.comentarPublicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncomentarPublicacionOperationCompleted);
            }
            this.InvokeAsync("comentarPublicacion", new object[] {
                        id_usuario,
                        id_publicacion,
                        contenido}, this.comentarPublicacionOperationCompleted, userState);
        }
        
        private void OncomentarPublicacionOperationCompleted(object arg) {
            if ((this.comentarPublicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.comentarPublicacionCompleted(this, new comentarPublicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void comentarPubCompletedEventHandler(object sender, comentarPubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class comentarPubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal comentarPubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void agregarPublicacionCompletedEventHandler(object sender, agregarPublicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarPublicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarPublicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerComentariosCompletedEventHandler(object sender, obtenerComentariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerComentariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerComentariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerPublicacionesContactosCompletedEventHandler(object sender, obtenerPublicacionesContactosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPublicacionesContactosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPublicacionesContactosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerPublicacionesIndividualesCompletedEventHandler(object sender, obtenerPublicacionesIndividualesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPublicacionesIndividualesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPublicacionesIndividualesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void comentarPublicacionCompletedEventHandler(object sender, comentarPublicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class comentarPublicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal comentarPublicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591