//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.JCargaMasiva4 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProyectosPortBinding", Namespace="http://Servicios/")]
    public partial class Proyectos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback S3OperationCompleted;
        
        private System.Threading.SendOrPostCallback S4OperationCompleted;
        
        private System.Threading.SendOrPostCallback S5OperationCompleted;
        
        private System.Threading.SendOrPostCallback S6OperationCompleted;
        
        private System.Threading.SendOrPostCallback S7OperationCompleted;
        
        private System.Threading.SendOrPostCallback leerProyectosOperationCompleted;
        
        private System.Threading.SendOrPostCallback asignarValorOperationCompleted;
        
        private System.Threading.SendOrPostCallback S8OperationCompleted;
        
        private System.Threading.SendOrPostCallback S06OperationCompleted;
        
        private System.Threading.SendOrPostCallback S05OperationCompleted;
        
        private System.Threading.SendOrPostCallback S01OperationCompleted;
        
        private System.Threading.SendOrPostCallback S04OperationCompleted;
        
        private System.Threading.SendOrPostCallback S03OperationCompleted;
        
        private System.Threading.SendOrPostCallback esUnEnteroOperationCompleted;
        
        private System.Threading.SendOrPostCallback S02OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Proyectos() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_JCargaMasiva4_Proyectos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event S3CompletedEventHandler S3Completed;
        
        /// <remarks/>
        public event S4CompletedEventHandler S4Completed;
        
        /// <remarks/>
        public event S5CompletedEventHandler S5Completed;
        
        /// <remarks/>
        public event S6CompletedEventHandler S6Completed;
        
        /// <remarks/>
        public event S7CompletedEventHandler S7Completed;
        
        /// <remarks/>
        public event leerProyectosCompletedEventHandler leerProyectosCompleted;
        
        /// <remarks/>
        public event asignarValorCompletedEventHandler asignarValorCompleted;
        
        /// <remarks/>
        public event S8CompletedEventHandler S8Completed;
        
        /// <remarks/>
        public event S06CompletedEventHandler S06Completed;
        
        /// <remarks/>
        public event S05CompletedEventHandler S05Completed;
        
        /// <remarks/>
        public event S01CompletedEventHandler S01Completed;
        
        /// <remarks/>
        public event S04CompletedEventHandler S04Completed;
        
        /// <remarks/>
        public event S03CompletedEventHandler S03Completed;
        
        /// <remarks/>
        public event esUnEnteroCompletedEventHandler esUnEnteroCompleted;
        
        /// <remarks/>
        public event S02CompletedEventHandler S02Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S3() {
            this.Invoke("S3", new object[0]);
        }
        
        /// <remarks/>
        public void S3Async() {
            this.S3Async(null);
        }
        
        /// <remarks/>
        public void S3Async(object userState) {
            if ((this.S3OperationCompleted == null)) {
                this.S3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS3OperationCompleted);
            }
            this.InvokeAsync("S3", new object[0], this.S3OperationCompleted, userState);
        }
        
        private void OnS3OperationCompleted(object arg) {
            if ((this.S3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S3Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S4() {
            this.Invoke("S4", new object[0]);
        }
        
        /// <remarks/>
        public void S4Async() {
            this.S4Async(null);
        }
        
        /// <remarks/>
        public void S4Async(object userState) {
            if ((this.S4OperationCompleted == null)) {
                this.S4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS4OperationCompleted);
            }
            this.InvokeAsync("S4", new object[0], this.S4OperationCompleted, userState);
        }
        
        private void OnS4OperationCompleted(object arg) {
            if ((this.S4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S4Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S5([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            this.Invoke("S5", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void S5Async(string arg0) {
            this.S5Async(arg0, null);
        }
        
        /// <remarks/>
        public void S5Async(string arg0, object userState) {
            if ((this.S5OperationCompleted == null)) {
                this.S5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS5OperationCompleted);
            }
            this.InvokeAsync("S5", new object[] {
                        arg0}, this.S5OperationCompleted, userState);
        }
        
        private void OnS5OperationCompleted(object arg) {
            if ((this.S5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S5Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S6() {
            this.Invoke("S6", new object[0]);
        }
        
        /// <remarks/>
        public void S6Async() {
            this.S6Async(null);
        }
        
        /// <remarks/>
        public void S6Async(object userState) {
            if ((this.S6OperationCompleted == null)) {
                this.S6OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS6OperationCompleted);
            }
            this.InvokeAsync("S6", new object[0], this.S6OperationCompleted, userState);
        }
        
        private void OnS6OperationCompleted(object arg) {
            if ((this.S6Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S6Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S7() {
            this.Invoke("S7", new object[0]);
        }
        
        /// <remarks/>
        public void S7Async() {
            this.S7Async(null);
        }
        
        /// <remarks/>
        public void S7Async(object userState) {
            if ((this.S7OperationCompleted == null)) {
                this.S7OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS7OperationCompleted);
            }
            this.InvokeAsync("S7", new object[0], this.S7OperationCompleted, userState);
        }
        
        private void OnS7OperationCompleted(object arg) {
            if ((this.S7Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S7Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void leerProyectos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ruta) {
            this.Invoke("leerProyectos", new object[] {
                        ruta});
        }
        
        /// <remarks/>
        public void leerProyectosAsync(string ruta) {
            this.leerProyectosAsync(ruta, null);
        }
        
        /// <remarks/>
        public void leerProyectosAsync(string ruta, object userState) {
            if ((this.leerProyectosOperationCompleted == null)) {
                this.leerProyectosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerProyectosOperationCompleted);
            }
            this.InvokeAsync("leerProyectos", new object[] {
                        ruta}, this.leerProyectosOperationCompleted, userState);
        }
        
        private void OnleerProyectosOperationCompleted(object arg) {
            if ((this.leerProyectosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerProyectosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool asignarValor([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("asignarValor", new object[] {
                        arg0,
                        arg1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void asignarValorAsync(string arg0, string arg1) {
            this.asignarValorAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void asignarValorAsync(string arg0, string arg1, object userState) {
            if ((this.asignarValorOperationCompleted == null)) {
                this.asignarValorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnasignarValorOperationCompleted);
            }
            this.InvokeAsync("asignarValor", new object[] {
                        arg0,
                        arg1}, this.asignarValorOperationCompleted, userState);
        }
        
        private void OnasignarValorOperationCompleted(object arg) {
            if ((this.asignarValorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.asignarValorCompleted(this, new asignarValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S8([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            this.Invoke("S8", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void S8Async(string arg0) {
            this.S8Async(arg0, null);
        }
        
        /// <remarks/>
        public void S8Async(string arg0, object userState) {
            if ((this.S8OperationCompleted == null)) {
                this.S8OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS8OperationCompleted);
            }
            this.InvokeAsync("S8", new object[] {
                        arg0}, this.S8OperationCompleted, userState);
        }
        
        private void OnS8OperationCompleted(object arg) {
            if ((this.S8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S8Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S06() {
            this.Invoke("S06", new object[0]);
        }
        
        /// <remarks/>
        public void S06Async() {
            this.S06Async(null);
        }
        
        /// <remarks/>
        public void S06Async(object userState) {
            if ((this.S06OperationCompleted == null)) {
                this.S06OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS06OperationCompleted);
            }
            this.InvokeAsync("S06", new object[0], this.S06OperationCompleted, userState);
        }
        
        private void OnS06OperationCompleted(object arg) {
            if ((this.S06Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S06Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S05([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            this.Invoke("S05", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void S05Async(string arg0) {
            this.S05Async(arg0, null);
        }
        
        /// <remarks/>
        public void S05Async(string arg0, object userState) {
            if ((this.S05OperationCompleted == null)) {
                this.S05OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS05OperationCompleted);
            }
            this.InvokeAsync("S05", new object[] {
                        arg0}, this.S05OperationCompleted, userState);
        }
        
        private void OnS05OperationCompleted(object arg) {
            if ((this.S05Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S05Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S01() {
            this.Invoke("S01", new object[0]);
        }
        
        /// <remarks/>
        public void S01Async() {
            this.S01Async(null);
        }
        
        /// <remarks/>
        public void S01Async(object userState) {
            if ((this.S01OperationCompleted == null)) {
                this.S01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS01OperationCompleted);
            }
            this.InvokeAsync("S01", new object[0], this.S01OperationCompleted, userState);
        }
        
        private void OnS01OperationCompleted(object arg) {
            if ((this.S01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S01Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S04() {
            this.Invoke("S04", new object[0]);
        }
        
        /// <remarks/>
        public void S04Async() {
            this.S04Async(null);
        }
        
        /// <remarks/>
        public void S04Async(object userState) {
            if ((this.S04OperationCompleted == null)) {
                this.S04OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS04OperationCompleted);
            }
            this.InvokeAsync("S04", new object[0], this.S04OperationCompleted, userState);
        }
        
        private void OnS04OperationCompleted(object arg) {
            if ((this.S04Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S04Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S03() {
            this.Invoke("S03", new object[0]);
        }
        
        /// <remarks/>
        public void S03Async() {
            this.S03Async(null);
        }
        
        /// <remarks/>
        public void S03Async(object userState) {
            if ((this.S03OperationCompleted == null)) {
                this.S03OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS03OperationCompleted);
            }
            this.InvokeAsync("S03", new object[0], this.S03OperationCompleted, userState);
        }
        
        private void OnS03OperationCompleted(object arg) {
            if ((this.S03Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S03Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esUnEntero([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("esUnEntero", new object[] {
                        arg0});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void esUnEnteroAsync(string arg0) {
            this.esUnEnteroAsync(arg0, null);
        }
        
        /// <remarks/>
        public void esUnEnteroAsync(string arg0, object userState) {
            if ((this.esUnEnteroOperationCompleted == null)) {
                this.esUnEnteroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnesUnEnteroOperationCompleted);
            }
            this.InvokeAsync("esUnEntero", new object[] {
                        arg0}, this.esUnEnteroOperationCompleted, userState);
        }
        
        private void OnesUnEnteroOperationCompleted(object arg) {
            if ((this.esUnEnteroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.esUnEnteroCompleted(this, new esUnEnteroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void S02() {
            this.Invoke("S02", new object[0]);
        }
        
        /// <remarks/>
        public void S02Async() {
            this.S02Async(null);
        }
        
        /// <remarks/>
        public void S02Async(object userState) {
            if ((this.S02OperationCompleted == null)) {
                this.S02OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS02OperationCompleted);
            }
            this.InvokeAsync("S02", new object[0], this.S02OperationCompleted, userState);
        }
        
        private void OnS02OperationCompleted(object arg) {
            if ((this.S02Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S02Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S3CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S4CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S5CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S6CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S7CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void leerProyectosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void asignarValorCompletedEventHandler(object sender, asignarValorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class asignarValorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal asignarValorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S8CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S06CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S05CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S01CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S04CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S03CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void esUnEnteroCompletedEventHandler(object sender, esUnEnteroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class esUnEnteroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal esUnEnteroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void S02CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591