//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.JDenuncia {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DenunciaPortBinding", Namespace="http://Servicios/")]
    public partial class Denuncia : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerTarDenunciadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerProDenunciadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPubDenunciadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerComDenunciadasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Denuncia() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_JDenuncia_Denuncia;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerTarDenunciadasCompletedEventHandler obtenerTarDenunciadasCompleted;
        
        /// <remarks/>
        public event obtenerProDenunciadasCompletedEventHandler obtenerProDenunciadasCompleted;
        
        /// <remarks/>
        public event obtenerPubDenunciadasCompletedEventHandler obtenerPubDenunciadasCompleted;
        
        /// <remarks/>
        public event obtenerComDenunciadasCompletedEventHandler obtenerComDenunciadasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerTarDenunciadas() {
            object[] results = this.Invoke("obtenerTarDenunciadas", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTarDenunciadasAsync() {
            this.obtenerTarDenunciadasAsync(null);
        }
        
        /// <remarks/>
        public void obtenerTarDenunciadasAsync(object userState) {
            if ((this.obtenerTarDenunciadasOperationCompleted == null)) {
                this.obtenerTarDenunciadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTarDenunciadasOperationCompleted);
            }
            this.InvokeAsync("obtenerTarDenunciadas", new object[0], this.obtenerTarDenunciadasOperationCompleted, userState);
        }
        
        private void OnobtenerTarDenunciadasOperationCompleted(object arg) {
            if ((this.obtenerTarDenunciadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTarDenunciadasCompleted(this, new obtenerTarDenunciadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerProDenunciadas() {
            object[] results = this.Invoke("obtenerProDenunciadas", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerProDenunciadasAsync() {
            this.obtenerProDenunciadasAsync(null);
        }
        
        /// <remarks/>
        public void obtenerProDenunciadasAsync(object userState) {
            if ((this.obtenerProDenunciadasOperationCompleted == null)) {
                this.obtenerProDenunciadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerProDenunciadasOperationCompleted);
            }
            this.InvokeAsync("obtenerProDenunciadas", new object[0], this.obtenerProDenunciadasOperationCompleted, userState);
        }
        
        private void OnobtenerProDenunciadasOperationCompleted(object arg) {
            if ((this.obtenerProDenunciadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerProDenunciadasCompleted(this, new obtenerProDenunciadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerPubDenunciadas() {
            object[] results = this.Invoke("obtenerPubDenunciadas", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPubDenunciadasAsync() {
            this.obtenerPubDenunciadasAsync(null);
        }
        
        /// <remarks/>
        public void obtenerPubDenunciadasAsync(object userState) {
            if ((this.obtenerPubDenunciadasOperationCompleted == null)) {
                this.obtenerPubDenunciadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPubDenunciadasOperationCompleted);
            }
            this.InvokeAsync("obtenerPubDenunciadas", new object[0], this.obtenerPubDenunciadasOperationCompleted, userState);
        }
        
        private void OnobtenerPubDenunciadasOperationCompleted(object arg) {
            if ((this.obtenerPubDenunciadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPubDenunciadasCompleted(this, new obtenerPubDenunciadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] obtenerComDenunciadas() {
            object[] results = this.Invoke("obtenerComDenunciadas", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerComDenunciadasAsync() {
            this.obtenerComDenunciadasAsync(null);
        }
        
        /// <remarks/>
        public void obtenerComDenunciadasAsync(object userState) {
            if ((this.obtenerComDenunciadasOperationCompleted == null)) {
                this.obtenerComDenunciadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerComDenunciadasOperationCompleted);
            }
            this.InvokeAsync("obtenerComDenunciadas", new object[0], this.obtenerComDenunciadasOperationCompleted, userState);
        }
        
        private void OnobtenerComDenunciadasOperationCompleted(object arg) {
            if ((this.obtenerComDenunciadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerComDenunciadasCompleted(this, new obtenerComDenunciadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerTarDenunciadasCompletedEventHandler(object sender, obtenerTarDenunciadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTarDenunciadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTarDenunciadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerProDenunciadasCompletedEventHandler(object sender, obtenerProDenunciadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerProDenunciadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerProDenunciadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerPubDenunciadasCompletedEventHandler(object sender, obtenerPubDenunciadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPubDenunciadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPubDenunciadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerComDenunciadasCompletedEventHandler(object sender, obtenerComDenunciadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerComDenunciadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerComDenunciadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591